source "https://rubygems.org"

ruby "3.3.6"

gem "rails", "~> 8.1"
gem "sqlite3", ">= 2.1"
gem "puma", "~> 6.4"
gem "rack-cors"
gem "paper_trail"
gem "rspec-rails"
gem "factory_bot_rails"
gem "jwt"
gem "rack-attack", require: false
gem "sidekiq"

group :development, :test do
  gem "debug"
end
